In [2]:
import numpy as np


In [3]:
arr= np.array([1,2,3,4,5,6])

In [4]:
arr


array([1, 2, 3, 4, 5, 6])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

# Dimensions in array

In [8]:
arr = np.array(20)
arr
type(arr)

numpy.ndarray

In [9]:
arr

array(20)

In [10]:
arr.ndim

0

# 1d array

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.ndim

1

# 2d array

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr.ndim

2

In [20]:
arr = np.array([[1.1,2.8,3.4],[4.2,5,6]])
arr

array([[1.1, 2.8, 3.4],
       [4.2, 5. , 6. ]])

# 3d array

In [21]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
arr.ndim

3


# Checking the Dimension of an array

In [25]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Numpy Array Indexing

Get the first element from the following array:

In [26]:
arr = np.array([1,2,3,4])
arr[0]

1

# get third and sixth and 8th elements from the following array and add them

In [27]:
m = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
m

array([41.  , 87.  , 34.  , 56.8 , 39.23, 90.  , 15.  , 10.  , 19.  ,
       56.  ])

In [28]:
print("the third element is", m[2])
print("the sixth element is", m[5])
print("the 8th element is", m[7])
print("sum of this elements are", m[2]+m[5]+m[7])

the third element is 34.0
the sixth element is 90.0
the 8th element is 10.0
sum of this elements are 134.0


# Access 2d array

In [31]:
arr = np.array([[10,20,30,40,50,],[60,70,80,90,100]])
print("2nd element on 1st row", arr[0,1])
print("4th element on 1st row", arr[0,3])
print("last element on 2nd row", arr[1,4])

2nd element on 1st row 20
4th element on 1st row 40
last element on 2nd row 100


# Add the first element of row 1 and last element

In [33]:
arr = np.array([[10,20,30,40,50,],[60,70,80,90,100]])
print("sum", arr[0,0]+arr[1,4])

sum 110


# Access 3d array

In [45]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [46]:
print(arr[0,1,2])

6


In [47]:
print(arr[1,1,2])

12


In [48]:
print(arr[1,0,1])

8


# Slicing of numpy arrays

In [50]:
arr = np.array([1,2,3,4,5,6,7])
arr[1:5]

array([2, 3, 4, 5])

In [51]:
arr[::2]

array([1, 3, 5, 7])

# Slicing in 2d Array

In [54]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
a[1,1:4]

array([70, 80, 90])

In [58]:
a[0,0:4]

array([10, 20, 30, 40])

# Checking the data type of an array

In [60]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [62]:
arr = np.array(['cat','dog','ant'])
arr.dtype

dtype('<U3')

# Create an arrays with a defined data type

In [64]:
arr = np.array([1,2,3,4], dtype = 'S')
arr.dtype


dtype('S1')

In [65]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

# Create an array with data types of 4 bytes integer

In [66]:
arr = np.array([1,2,3,4], dtype = 'i4')
arr

array([1, 2, 3, 4])

In [67]:
arr.dtype

dtype('int32')

# Numpy array Shape

The shape of an array is the number of elements in each dimension

# 2d array

In [68]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
arr.shape

(2, 4)

# 3d array

In [70]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
arr.dtype

dtype('int32')

In [71]:
arr.ndim

3

In [72]:
arr.shape

(1, 3, 4)

# Joining Numpy Arrays

In [74]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

# Join 2d array

In [75]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [76]:
np.concatenate((arr1,arr2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Splitting Numpy Arrays

splitting the array in 3 parts

In [78]:
arr = np.array([1,2,3,4,5,6])
np.array_split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

splitting the array in 4 parts

In [79]:
np.array_split(arr,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

# Ravel & Flatten

Converts multidimensional array into 1d array

In [80]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
m.ndim

3

In [81]:
m

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [89]:
newarray = m.ravel()
print(newarray)
print("Now the new dimension is", newarray.ndim)

[1 2 3 4 5 6 7 8 9]
Now the new dimension is 1


In [90]:
newarray = m.flatten()
print(newarray)
print("Now the new dimension is", newarray.ndim)

[1 2 3 4 5 6 7 8 9]
Now the new dimension is 1


In [92]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(c.ndim)
print(c)

4
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [93]:
newarr = c.flatten()
print(newarr)
print("Now the new dimension is", newarr.ndim)

[1 2 3 4 5 6 7 8 9]
Now the new dimension is 1


In [95]:
newarr = c.ravel()
print(newarr)
print("Now the new dimension is", newarr.ndim)

[1 2 3 4 5 6 7 8 9]
Now the new dimension is 1


# Unique Function

In [97]:
k = np.array([12,14,6,5,7,8,91,25,3,6,5,8,45,68])
k

array([12, 14,  6,  5,  7,  8, 91, 25,  3,  6,  5,  8, 45, 68])

In [98]:
np.unique(k)

array([ 3,  5,  6,  7,  8, 12, 14, 25, 45, 68, 91])

In [102]:
np.unique(k, return_index = True, return_counts = True)

(array([ 3,  5,  6,  7,  8, 12, 14, 25, 45, 68, 91]),
 array([ 8,  3,  2,  4,  5,  0,  1,  7, 12, 13,  6], dtype=int64),
 array([1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

# Delete

In [103]:
a = np.array([12,13,14,15])
a

array([12, 13, 14, 15])

In [104]:
np.delete(a,[1])

array([12, 14, 15])

In [105]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
x

array([[ 2,  7,  9,  6,  8],
       [ 4,  5,  7,  1,  2],
       [50,  0, 65,  6,  7]])

In [108]:
np.delete(x,1,0)

array([[ 2,  7,  9,  6,  8],
       [50,  0, 65,  6,  7]])