In [2]:
import numpy as np


In [3]:
arr= np.array([1,2,3,4,5,6])

In [4]:
arr


array([1, 2, 3, 4, 5, 6])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

# Dimensions in array

In [8]:
arr = np.array(20)
arr
type(arr)

numpy.ndarray

In [9]:
arr

array(20)

In [10]:
arr.ndim

0

# 1d array

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.ndim

1

# 2d array

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr.ndim

2

In [20]:
arr = np.array([[1.1,2.8,3.4],[4.2,5,6]])
arr

array([[1.1, 2.8, 3.4],
       [4.2, 5. , 6. ]])

# 3d array

In [21]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
arr.ndim

3


# Checking the Dimension of an array

In [25]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Numpy Array Indexing

Get the first element from the following array:

In [26]:
arr = np.array([1,2,3,4])
arr[0]

1

# get third and sixth and 8th elements from the following array and add them

In [27]:
m = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
m

array([41.  , 87.  , 34.  , 56.8 , 39.23, 90.  , 15.  , 10.  , 19.  ,
       56.  ])

In [28]:
print("the third element is", m[2])
print("the sixth element is", m[5])
print("the 8th element is", m[7])
print("sum of this elements are", m[2]+m[5]+m[7])

the third element is 34.0
the sixth element is 90.0
the 8th element is 10.0
sum of this elements are 134.0


# Access 2d array

In [31]:
arr = np.array([[10,20,30,40,50,],[60,70,80,90,100]])
print("2nd element on 1st row", arr[0,1])
print("4th element on 1st row", arr[0,3])
print("last element on 2nd row", arr[1,4])

2nd element on 1st row 20
4th element on 1st row 40
last element on 2nd row 100


# Add the first element of row 1 and last element

In [33]:
arr = np.array([[10,20,30,40,50,],[60,70,80,90,100]])
print("sum", arr[0,0]+arr[1,4])

sum 110


# Access 3d array

In [38]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
print(arr[0,1,2])

6


In [41]:
print(arr[1,1,2])

12


In [43]:
print(arr[1,0,1])

8
